### ISSUE TITLE
Separate packages for building/developing vs querying db?

### ISSUE THREAD

**Issue by levisc8** [levisc8/Padrino#1]
Food for thought. I think that _if_ this ends up as an SQL data base, then we (I) will need to write a series of wrappers from R/Excel to help those who are less familiar with how that works contribute to it's development. That said, those wrappers should probably not be in a package that we distribute to the public to help them access it (I'm imagining how messy that might get if someone accidentally calls the wrong function and wipes out half the data base).

For now, I'll keep this repo for the development/building side which can house functions we then distribute to Padrino-digitizers (side note: we need a clever name for them). When the data base is a bit more mature, depending on it's form, I may create a separate package called something like `RPadrino` and that would be what actually goes to `CRAN`/`ROpenSci` for the general public to use for querying. Happy to hear thoughts on this idea.

@robcito @dzchilds

**Comment by dzchilds** [comment]
I would definitely keep these quite separate. For now, its makes sense to sketch out the minimal 'low-level' R data structures used to store an IPM. I think this should be nothing more than the domain of the states, component vital rate functions, and kernel functions. My view is that these should not be formal R functions, but something else. Once this is defined carefully, it should be easy enough to parse these into iteration kernels. Similarly, writing functions that read the Padrino database (whatever it ends up being) will be much easier once this is done. In terms of fleshing out the design of all this, I like Steve's suggestion -- work out what you want to be able to do with the IPMs before embarking on the software design.
